"""Render publications.html from cv/publications.yaml.

Usage (from the repo root):
    python3 scripts/build_publications.py
"""

from html import escape
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
OWNER = "W Lehn-Schiøler"

HEAD = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Publications | William Theodor</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <!-- Generated by scripts/build_publications.py from cv/publications.yaml; edit that file, not this one. -->
    <canvas id="eeg-bg"></canvas>
    <div class="container">
        <h1>Publications</h1>
        <p class="page-intro">Journal articles, conference papers and preprints. A continuously updated list is available on <a href="https://scholar.google.com/citations?user=7K_-v1UAAAAJ&hl=en&oi=ao" target="_blank" rel="noopener noreferrer">Google Scholar</a>.</p>
"""

FOOT = """
        <a href="index.html" class="back-btn">← Back to Home</a>
    </div>
    <script src="eeg-animation.js"></script>
</body>
</html>
"""


def link_label(url):
    return "arXiv" if "arxiv.org" in url else "DOI"


def card(p, default_tag=None):
    tag = p.get("tag", default_tag)
    authors = escape(p["authors"]).replace(OWNER, f"<strong>{OWNER}</strong>")
    lines = [
        '            <div class="project-card">',
        '                <div class="pub-meta">',
        f'                    <span class="pub-year">{p["year"]}</span>',
    ]
    if tag:
        lines.append(f'                    <span class="pub-tag">{escape(tag)}</span>')
    elif p.get("citations"):
        n = p["citations"]
        lines.append(f'                    <span class="pub-citations">{n} citation{"s" if n != 1 else ""}</span>')
    lines += [
        "                </div>",
        f"                <h4>{escape(p['title'])}</h4>",
        f'                <p class="pub-authors">{authors}</p>',
        f'                <p class="pub-venue">{escape(p.get("web_venue", p["venue"]))}</p>',
    ]
    if p.get("url"):
        lines += [
            '                <div class="paper-links">',
            f'                    <a href="{escape(p["url"])}" class="paper-link" target="_blank" rel="noopener noreferrer">{link_label(p["url"])}</a>',
            "                </div>",
        ]
    lines.append("            </div>")
    return "\n".join(lines)


def section(title, pubs, default_tag=None):
    cards = "\n\n".join(card(p, default_tag) for p in pubs)
    return (
        f'\n        <h3 class="section-title">{title}</h3>\n'
        '        <div class="projects-list">\n\n'
        f"{cards}\n\n"
        "        </div>\n"
    )


def main():
    data = yaml.safe_load((ROOT / "cv" / "publications.yaml").read_text(encoding="utf-8"))
    html = (
        HEAD
        + section("Preprints &amp; Under Review", data["preprints"], default_tag="Preprint")
        + section("Peer-Reviewed", data["peer_reviewed"])
        + FOOT
    )
    (ROOT / "publications.html").write_text(html, encoding="utf-8")


if __name__ == "__main__":
    main()
